version: '3'

# TODO: make volume for database
services:
  database:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
  
  hoverfly:
    container_name: hoverfly
    image: spectolabs/hoverfly:v1.3.4
    command: 
      - "-webserver"
      - "-response-body-files-path=/hoverfly_app/responses"
      - "-import=/hoverfly_app/simulations/recommend.simulation.json"
    volumes:
      - "$PWD/hoverfly:/hoverfly_app:ro"
    ports:
      - "8500:8500"
    
